version: '3'
services:

  #PHP Service
  app:
    image: leandroschelb/php_composer:0.2.1
    container_name: php_coppertec_api
    restart: unless-stopped
    tty: true
    environment:
      SERVICE_NAME: app
      SERVICE_TAGS: dev
    working_dir: /var/www
    volumes:
      - .:/var/www
      - ./php/local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - app-network

  #Nginx Service
  webserver:
    image: nginx:alpine
    container_name: nginx_coppertec_api
    restart: unless-stopped
    tty: true
    ports:
      - "8000:80"
      - "443:443"
    volumes:
      - .:/var/www
      - ./nginx/conf.d/:/etc/nginx/conf.d/
    networks:
      - app-network

  #MySQL Service
  db:
    image: mysql:5.7.22
    container_name: mysql_coppertec_api
    restart: unless-stopped
    tty: true
    environment:
      MYSQL_DATABASE: coppertec_api
      MYSQL_ROOT_PASSWORD: senha_root
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    ports:
      - "3306:3306"
    volumes:
      - dbdata:/var/lib/mysql/
      - ./mysql/my.cnf:/etc/mysql/my.cnf
    networks:
      - app-network
    
  #SQLite Database para testes
  sqlite3:
    image: nouchka/sqlite3:latest
    container_name: sqlite_coppertec_api
    stdin_open: true
    tty: true
    volumes:
      - ./sqlite_db_teste/:/root/db/
    networks:
      - app-network

#Docker Networks
networks:
  app-network:
    driver: bridge
#Volumes
volumes:
  dbdata:
    driver: local
